# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b0a7ee82c417588ec911b15ff0f12f885216ce50b2d8a70ece53696ca2616e029fe0b7eae9c7f32a90dd2470632e5453fa9e3c27119ec1a1d4ec68c3283609c

test:
  secret_key_base: 389b7e0d5fc4c978eea4a449cae984093f7b428813a0a19f95fc3c1d88b4eba13d500ac4365181a5f094ac94f902f01fcbf51881e23dfeb8af8bf28856234534

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
